name: "Hello Actions"
description: "Greet someone"
author: "mour.keita@gmail.com"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"
    
 runs:
   using: "docker"
   image: "Dockerfile"
   
 brandng:
   icon: "mic"
   color: "purple"
